In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
#Code here
v = np.zeros(10, dtype=int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [7]:
#Code here
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

arr = np.random.random(size=rows*cols).reshape(rows, cols)
print(arr)
print(np.mean(arr))

Enter number of rows: 2
Enter number of columns: 3
[[0.35481838 0.25335715 0.8478739 ]
 [0.10309602 0.56938745 0.44481137]]
0.42889071025594405


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [10]:
#Code here
def bordered_array(a, b):
    arr = np.ones((a, b), dtype=int)
    if a > 1 and b > 1:
        arr[1:a-1, 1:b-1] = 0
    return arr

print(bordered_array(4, 4))
print(bordered_array(3, 5))
print(bordered_array(1, 5))
print(bordered_array(5, 1))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]]
[[1]
 [1]
 [1]
 [1]
 [1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [16]:
#Code here
print(np.random.random(10))

[0.86712175 0.32163245 0.44087587 0.4891965  0.26842846 0.73839671
 0.66307365 0.87681599 0.02546319 0.11836423]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [18]:
#Code here
# though identity matrix is a square matrix, but numpy's method will give no error in this case
identity_matrix = np.eye(3, 4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [20]:
#Code here
np.random.randint(0, 5, 25).reshape(5, 5)

array([[1, 3, 0, 0, 3],
       [2, 0, 2, 3, 1],
       [1, 1, 3, 3, 4],
       [1, 3, 1, 3, 2],
       [1, 4, 4, 4, 4]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [36]:
#code here
def distance(arr, point):
    dist = (np.sum((arr - point)**2, axis=1)**(1./2)).astype(int)
    return dist

v = np.random.randint(1, 101, 20).reshape(10, 2)
point = np.array([2,3])
distance(v, point)

array([ 75, 104, 128,  82,  55,  30,  77,  71,  91, 103])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
# Code here
shape = (6, 7, 8)
index_of_element = 99 # 100th element (0-indexed)

dim2_size = shape[2] # 8
dim1_dim2_product = shape[1] * shape[2] # 7 * 8 = 56

x = index_of_element // dim1_dim2_product
remaining_index = index_of_element % dim1_dim2_product
y = remaining_index // dim2_size
z = remaining_index % dim2_size

print(f"The index (x,y,z) of the 100th element is: ({x}, {y}, {z})")

The index (x,y,z) of the 100th element is: (1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [43]:
#Code here
arr = np.array([1, 2, 3, 4, -8, -10])
arr[::-1].astype(float)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [45]:
#Code here
arr = np.array([1, 2])
arr.size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [47]:
#Code here
def softmax(arr):
    exps = np.exp(arr)
    return exps/np.sum(exps)

arr = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
softmax(arr)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [49]:
#Coder here
def vertical_stack_arrays(*arrays):
    if not arrays:
        return np.array([])

    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays.")

    # Perform vertical stacking
    return np.vstack(arrays)

a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
print(vertical_stack_arrays(a, b))

c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695], [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])
print(vertical_stack_arrays(a, b, c))

try:
    print(vertical_stack_arrays(a, [1, 2, 3]))
except TypeError as e:
    print(f"\nError: {e}")

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]

Error: All inputs must be NumPy arrays.


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [52]:
#Code here
def date_array(start, end):
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both 'start' and 'end' dates must be strings.")

    start_date = np.datetime64(start)
    end_date = np.datetime64(end)

    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')

    return dates.astype(str)


try:
    print("Example 1 Output:")
    print(date_array(start = '2020-09-15', end = '2020-09-25'))

    print("\nExample 2 Output:")
    print(date_array(start = '2022-12-01', end = '2022-12-06'))

    print("\nExample 3 Output:")
    print(date_array(start = '2020-11-25', end = '2020-11-30'))
    print(date_array(start = '2020-09-15', end = 2020))
except TypeError as e:
    print(f"\nError: {e}")

Example 1 Output:
['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']

Example 2 Output:
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06']

Example 3 Output:
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']

Error: Both 'start' and 'end' dates must be strings.


### `Q-14:` Subtract the mean of each row from a matrix.

In [63]:
#code here
arr = np.arange(20).reshape(4, 5)
print(arr)
arr - np.mean(arr, axis=1, keepdims=True)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [66]:
#Code here
arr = np.arange(20).reshape(4, 5)
print(arr)
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  0  2  3  4]
 [ 6  5  7  8  9]
 [11 10 12 13 14]
 [16 15 17 18 19]]


### `Q-16:` Replace odd elements in arrays with -1.

In [67]:
#Code here
arr = np.arange(20).reshape(4, 5)
print(arr)
arr[arr%2==1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [71]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.max([a, b], axis=0)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [72]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7634, 5182, 7680, 1701, 4932],
       [8886, 3984, 4599, 8096, 5324],
       [2139, 6654, 3610, 2544, 4331],
       [8612, 2233, 7485, 1055, 2546],
       [7353,  576, 7392, 7819,  661],
       [2013, 3107, 7041, 5120,  934],
       [1058, 1423, 8315, 7989, 3496],
       [2885, 1144, 8759, 9528, 9787]])

In [74]:
# Code here
alter = arr1[:, ::2]
print("1. Every alternate column of the array:")
print(alter)

x_min = arr1.min()
x_max = arr1.max()

if (x_max - x_min) == 0:
    normalized = np.zeros_like(arr1, dtype=float)
else:
    normalized = (arr1 - x_min) / (x_max - x_min)

print("\n2. Normalized array:")
print(normalized)

1. Every alternate column of the array:
[[7634 7680 4932]
 [8886 4599 5324]
 [2139 3610 4331]
 [8612 7485 2546]
 [7353 7392  661]
 [2013 7041  934]
 [1058 8315 3496]
 [2885 8759 9787]]

2. Normalized array:
[[0.76625774 0.50005428 0.77125176 0.12213658 0.47291282]
 [0.90218217 0.3699924  0.4367604  0.81641516 0.51547063]
 [0.16968842 0.65986321 0.32938877 0.21365758 0.40766475]
 [0.87243513 0.17989361 0.75008142 0.05200304 0.21387472]
 [0.73575073 0.         0.7399848  0.78634242 0.0092281 ]
 [0.15600912 0.27478015 0.70187819 0.4933232  0.03886657]
 [0.05232874 0.09195527 0.84019108 0.80479861 0.31701227]
 [0.25067854 0.0616654  0.88839431 0.97188145 1.        ]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [78]:
#Code here
def find_nth_largest(arr, n):
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise TypeError("Input 'arr' must be a 1D NumPy array.")

    if not isinstance(n, int) or n < 1 or n > len(arr):
        raise ValueError(f"Input 'n' must be an integer between 1 and {len(arr)} (inclusive).")

    arr = np.sort(arr)[::-1]

    return arr[n - 1]


arr1 = np.array([12, 34, 40, 7, 1, 0])
n1 = 3
print(arr1)
find_nth_largest(arr1, n1)


[12 34 40  7  1  0]


np.int64(12)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [81]:
#code here
a = np.array([1, 2, 3])

n = len(a)

# [1, 1, 1, 2, 2, 2, 3, 3, 3]
part1 = np.repeat(a, n)

# [1, 2, 3, 1, 2, 3, 1, 2, 3]
part2 = np.tile(a, n)

np.concatenate((part1, part2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])