## **Convolution**

### **Convolution from Scratch**

In [22]:
import numpy as np

In [23]:
def pad_image(image, pad):
    return np.pad(image, ( (pad, pad), (pad, pad), (0,0)), mode='constant', constant_values=0)

def convolve_rgb(image, kernel, stride = (1,1), padding = 0 ):
    if padding > 0:
        image = pad_image(image, padding)

    image_h, image_w, image_c = image.shape
    kernel_h, kernel_w, kernel_c = kernel.shape
    stride_h, stride_w = stride

    output_h = ( image_h - kernel_h ) // stride_h + 1
    output_w = ( image_w - kernel_w ) // stride_w + 1

    output = np.zeros( (output_h, output_w) )

    for i in range(output_h):
        for j in range(output_w):

            h_start = i * stride_h
            h_end = h_start + kernel_h
            w_start = j * stride_w
            w_end = w_start + kernel_w

            image_window = image[h_start:h_end, w_start:w_end, :]

            output[i, j] = np.sum(image_window * kernel)

    return output

In [24]:
sample_image = np.ones((5, 5, 3))
sample_kernel = np.zeros((3, 3, 3))
sample_kernel[1, 1, :] = 1

In [25]:
result = convolve_rgb(sample_image, sample_kernel, stride=(2, 2), padding=1)

print("Output Shape:", result.shape)
print("Output Matrix:\n", result)

Output Shape: (3, 3)
Output Matrix:
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


### **Convolution using Keras**

In [26]:
import tensorflow as tf
from tensorflow.keras import layers, models

input_shape = (5, 5, 3)

model = models.Sequential()

model.add(layers.Input(shape=input_shape))

model.add(layers.Conv2D(1, (3,3), padding="same", strides=(2,2)))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)               │ (None, 3, 3, 1)        │            28 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28 (112.00 B)

 Trainable params: 28 (112.00 B)

 Non-trainable params: 0 (0.00 B)