### **What is numpy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the **ndarray** object. This encapsulates n-dimensional arrays of homogeneous data types

### **Numpy Arrays Vs Python Sequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### **Creating Numpy Arrays**

In [ ]:
# np.array
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
print(np.arange(1, 11))
print(np.arange(1, 11, 2))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# with reshape
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.19114491, 0.63664463, 0.94511921, 0.42189564],
       [0.04627783, 0.36415489, 0.78887   , 0.26744925],
       [0.6939958 , 0.79104431, 0.33287406, 0.61405625]])

In [ ]:
# np.linspace
# lower range, upper range, how many items
print(np.linspace(-10, 10, 10))
print(np.linspace(-10,10,10,dtype=int))

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# np.identity -> identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Attributes**

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim -> to find number of dimensions
a3.ndim

3

In [ ]:
# shape -> to find the structure
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size -> number of items
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize -> each item how much memory
print(a3.itemsize)
print(a2.itemsize)
print(a1.itemsize)

8
8
4


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### **Changing Datatype**

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### **Scalar Operations**

In [ ]:
# arithmetic operators
print(a1 * 2)
print()
print(a1 + 2)
print()
print(a1 - 2)
print()
print(a1 / 2)
print()
print(a1 % 2)
print()
print(a1 ** 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
# relational operators
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

#### **Vector Operations**

In [ ]:
# arithmetic
print(a1 + a2)
print()
print(a1 - a2)
print()
print(a1 * a2)
print()
print(a1 ** a2)
print()
print(a1 / a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


### **Array Functions**

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[70., 35., 14.],
       [76.,  6., 57.],
       [24.,  4., 19.]])

In [ ]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
# 0 -> col and 1 -> row
print(np.max(a1, axis=1))
print(np.min(a1, axis=1))
print(np.sum(a1, axis=1))
print(np.prod(a1,axis=0))

76.0
4.0
305.0
1626142694400.0
[70. 76. 24.]
[14.  6.  4.]
[119. 139.  47.]
[127680.    840.  15162.]


In [ ]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print(np.var(a1,axis=1))

33.888888888888886
24.0
25.817498133563273
666.5432098765431
[533.55555556 873.55555556  72.22222222]


In [ ]:
# trigonomoetric functions
print(np.sin(a1))

[[ 0.77389068 -0.42818267  0.99060736]
 [ 0.56610764 -0.2794155   0.43616476]
 [-0.90557836 -0.7568025   0.14987721]]


In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# log and exponents
print(a1)
print(np.log(a1))
print(np.log10(a1))
print(np.exp(a1))

[[70. 35. 14.]
 [76.  6. 57.]
 [24.  4. 19.]]
[[4.24849524 3.55534806 2.63905733]
 [4.33073334 1.79175947 4.04305127]
 [3.17805383 1.38629436 2.94443898]]
[[1.84509804 1.54406804 1.14612804]
 [1.88081359 0.77815125 1.75587486]
 [1.38021124 0.60205999 1.2787536 ]]
[[2.51543867e+30 1.58601345e+15 1.20260428e+06]
 [1.01480039e+33 4.03428793e+02 5.68572000e+24]
 [2.64891221e+10 5.45981500e+01 1.78482301e+08]]


In [ ]:
# round/floor/ceil
x = np.random.random((2,3))*100
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))

[[ 7. 33. 70.]
 [71. 52. 33.]]
[[ 7. 33. 70.]
 [71. 52. 33.]]
[[ 8. 34. 71.]
 [72. 53. 34.]]


### **Indexing and Slicing**

#### **Indexing**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# indexing on 1D arrays
print(a1)
print(a1[0])
print(a1[-1])

[0 1 2 3 4 5 6 7 8 9]
0
9


In [ ]:
# indexing on 2D arrays
print(a2)
print(a2[1,2])
# print(a2[1][2])
print(a2[1,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
4


In [ ]:
# indexing on 3D
print(a3)
print(a3[1, 0, 1])
print(a3[0, 1, 0])
print(a3[1, 1, 0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
2
6


#### **Slicing**

In [ ]:
# Slicing on 1D arrays -> all are same as python
print(a1)
print(a1[2:5])
print(a1[2:5:2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]


In [ ]:
# slicing on 2D arrays
# arr[ rows_start : rows_end + 1 : step , cols_start : cols_end+1 : step]
print(a2)
print("*"*20)

print(a2[0,0]) # single element
print("*"*20)

print(a2[0, :]) # to find only the first row
print("*"*20)

print(a2[:, 2]) # to find only the third column
print("*"*20)

print(a2[1:, 1:3])
print("*"*20)

print(a2[::2, ::3])
print("*"*20)

print(a2[::2, 1::2])
print("*"*20)

print(a2[1::2, ::3])
print("*"*20)

print(a2[:2, 1:])
print("*"*20)

print(a2[:2, 1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
********************
0
********************
[0 1 2 3]
********************
[ 2  6 10]
********************
[[ 5  6]
 [ 9 10]]
********************
[[ 0  3]
 [ 8 11]]
********************
[[ 1  3]
 [ 9 11]]
********************
[[4 7]]
********************
[[1 2 3]
 [5 6 7]]
********************
[[1 3]
 [5 7]]


In [ ]:
# Slicing on 3D Arrays
a3 = np.arange(27).reshape(3,3,3)
print(a3)
print("*"*20)

print(a3[1])
print("*"*20)

print(a3[::2])
print("*"*20)

print(a3[0, 1, :])
print("*"*20)

print(a3[1, :, 1])
print("*"*20)

print(a3[2, 1:, 1:])
print("*"*20)

print(a3[::2, 0, ::2])
print("*"*20)



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
********************
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
********************
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
********************
[3 4 5]
********************
[10 13 16]
********************
[[22 23]
 [25 26]]
********************
[[ 0  2]
 [18 20]]


### **Iterating**

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### **Reshaping**

In [ ]:
# reshape

In [ ]:
# Transpose
print(a2)
print(np.transpose(a2))
x = a2.T
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# ravel
print(a2.ravel())
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### **Stacking**

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **Splitting**

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(np.hsplit(a4,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]