In [1]:
import numpy as np

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
a = np.random.randint(1, 100, 15)
print(a)

[50 70 67 93 18  3 71 89 44 37 71 89 23  2  5]


In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[42 81 23 39]
 [64 54 51 53]
 [97 84 46 27]
 [93 22 49 67]
 [68 12 72 19]
 [39 58 69  4]]


In [4]:
print( np.sort(a) ) # ascending
print( np.sort(a)[::-1] ) # descending

[ 2  3  5 18 23 37 44 50 67 70 71 71 89 89 93]
[93 89 89 71 71 70 67 50 44 37 23 18  5  3  2]


In [5]:
print(np.sort(b)) # row wise ascending
print(np.sort(b, axis=0)) # column wise ascending

[[23 39 42 81]
 [51 53 54 64]
 [27 46 84 97]
 [22 49 67 93]
 [12 19 68 72]
 [ 4 39 58 69]]
[[39 12 23  4]
 [42 22 46 19]
 [64 54 49 27]
 [68 58 51 39]
 [93 81 69 53]
 [97 84 72 67]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
a = np.append(a,200)
print(a)

[ 50  70  67  93  18   3  71  89  44  37  71  89  23   2   5 200]


In [7]:
b

array([[42, 81, 23, 39],
       [64, 54, 51, 53],
       [97, 84, 46, 27],
       [93, 22, 49, 67],
       [68, 12, 72, 19],
       [39, 58, 69,  4]])

In [8]:
# adding columns to the right
np.append(
    b,
    np.ones((b.shape[0], 1)), axis = 1
)

array([[42., 81., 23., 39.,  1.],
       [64., 54., 51., 53.,  1.],
       [97., 84., 46., 27.,  1.],
       [93., 22., 49., 67.,  1.],
       [68., 12., 72., 19.,  1.],
       [39., 58., 69.,  4.,  1.]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[4.20000000e+01, 8.10000000e+01, 2.30000000e+01, 3.90000000e+01,
        7.64113497e-01],
       [6.40000000e+01, 5.40000000e+01, 5.10000000e+01, 5.30000000e+01,
        2.76829114e-01],
       [9.70000000e+01, 8.40000000e+01, 4.60000000e+01, 2.70000000e+01,
        6.35467029e-01],
       [9.30000000e+01, 2.20000000e+01, 4.90000000e+01, 6.70000000e+01,
        8.15492019e-02],
       [6.80000000e+01, 1.20000000e+01, 7.20000000e+01, 1.90000000e+01,
        5.16439014e-01],
       [3.90000000e+01, 5.80000000e+01, 6.90000000e+01, 4.00000000e+00,
        5.87470450e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
print(np.concatenate((c,d),axis=0))
print()
print(np.concatenate((c,d),axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [12]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
print( np.unique(e) )

[1 2 3 4 5 6]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [14]:
# code
a.shape

(16,)

In [15]:
np.expand_dims(a,axis=0).shape

(1, 16)

In [16]:
np.expand_dims(a,axis=1).shape

(16, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [17]:
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [18]:
# find all indices with value greater than 50
np.where( a > 50 )

(array([ 1,  2,  3,  6,  7, 10, 11, 15]),)

In [19]:
# replace all values > 50 with 0
np.where(a>50, 0, a)

array([50,  0,  0,  0, 18,  3,  0,  0, 44, 37,  0,  0, 23,  2,  5,  0])

In [20]:
np.where(a%2 == 0, 0, a)

array([ 0,  0, 67, 93,  0,  3, 71, 89,  0, 37, 71, 89, 23,  0,  5,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [21]:
# code
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [22]:
np.argmax(a)

np.int64(15)

In [25]:
b

array([[42, 81, 23, 39],
       [64, 54, 51, 53],
       [97, 84, 46, 27],
       [93, 22, 49, 67],
       [68, 12, 72, 19],
       [39, 58, 69,  4]])

In [27]:
print(np.argmax(b,axis=0)) # column wise max element index
print( np.argmax(b, axis=1)) # row wise max element index

[2 2 4 3]
[1 0 0 0 2 2]


In [28]:
# np.argmin
np.argmin(a)

np.int64(13)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [30]:
np.cumsum(a)

array([ 50, 120, 187, 280, 298, 301, 372, 461, 505, 542, 613, 702, 725,
       727, 732, 932])

In [31]:
b

array([[42, 81, 23, 39],
       [64, 54, 51, 53],
       [97, 84, 46, 27],
       [93, 22, 49, 67],
       [68, 12, 72, 19],
       [39, 58, 69,  4]])

In [33]:
np.cumsum(b)

array([  42,  123,  146,  185,  249,  303,  354,  407,  504,  588,  634,
        661,  754,  776,  825,  892,  960,  972, 1044, 1063, 1102, 1160,
       1229, 1233])

In [35]:
print( np.cumsum(b,axis=1) ) # row wise cumsum
print()
print( np.cumsum(b, axis=0)) # col wise cumsum

[[ 42 123 146 185]
 [ 64 118 169 222]
 [ 97 181 227 254]
 [ 93 115 164 231]
 [ 68  80 152 171]
 [ 39  97 166 170]]

[[ 42  81  23  39]
 [106 135  74  92]
 [203 219 120 119]
 [296 241 169 186]
 [364 253 241 205]
 [403 311 310 209]]


In [36]:
# np.cumprod
np.cumprod(a)

array([                  50,                 3500,               234500,
                   21808500,            392553000,           1177659000,
                83613789000,        7441627221000,      327431597724000,
          12114969115788000,   860162807220948000,  2767513547826165536,
        8312579378873152480, -1821585315963246656, -9107926579816233280,
        4642347333998953984])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [38]:
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [39]:
print( np.percentile(a, 100))
print()
print(np.percentile(a,0))
print()
print(np.percentile(a,50))

200.0

2.0

58.5


In [41]:
print(np.median(a))

58.5


### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [42]:
# code
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [45]:
bins = np.arange(0, 201, 10)
np.histogram(a, bins=bins)

(array([3, 1, 1, 1, 1, 1, 1, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
        130, 140, 150, 160, 170, 180, 190, 200]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [46]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [47]:
# code
a


array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [50]:
items = [10,20,30,40,50,60,70,80,90,100]
print(np.isin(a, items))
print(a[np.isin(a,items)])

[ True  True False False False False False False False False False False
 False False False False]
[50 70]


### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [51]:
# code
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [52]:
np.flip(a)

array([200,   5,   2,  23,  89,  71,  37,  44,  89,  71,   3,  18,  93,
        67,  70,  50])

In [57]:
print(b)
print()
print(np.flip(b))
print()
print(np.flip(b, axis=0))
print()
print(np.flip(b,axis=1))

[[42 81 23 39]
 [64 54 51 53]
 [97 84 46 27]
 [93 22 49 67]
 [68 12 72 19]
 [39 58 69  4]]

[[ 4 69 58 39]
 [19 72 12 68]
 [67 49 22 93]
 [27 46 84 97]
 [53 51 54 64]
 [39 23 81 42]]

[[39 58 69  4]
 [68 12 72 19]
 [93 22 49 67]
 [97 84 46 27]
 [64 54 51 53]
 [42 81 23 39]]

[[39 23 81 42]
 [53 51 54 64]
 [27 46 84 97]
 [67 49 22 93]
 [19 72 12 68]
 [ 4 69 58 39]]


### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [58]:
# code
a

array([ 50,  70,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [61]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [62]:
# code
a

array([110, 530,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [64]:
np.delete(a, [0])

array([530,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,   2,
         5, 200])

In [65]:
np.delete(a,[0,2,4])

array([530,  93,   3,  71,  89,  44,  37,  71,  89,  23,   2,   5, 200])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [66]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
np.intersect1d(m,n)

array([3, 4, 5])

In [68]:
np.setdiff1d(n,m)

array([6, 7])

In [69]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [70]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [71]:
# code
a

array([110, 530,  67,  93,  18,   3,  71,  89,  44,  37,  71,  89,  23,
         2,   5, 200])

In [72]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 67, 75, 25, 25, 71, 75, 44, 37, 71, 75, 25, 25, 25, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals